### ISSUE TITLE
How to use v3 api?

### ISSUE THREAD

**Issue by fahribaharudin** [Cyvelnet/Laravel5-billplz#2]
Can we use v3 api with this package?

**Comment by Cyvelnet** [comment]
im preparing for v1 release, which will add billplz v3 api, billplz sandbox support, and also a much more readable way to send a bill like

`Billplz::send(new MonthlyManagementBill())
        ->to('Mr. Foobar')
        ->viaEmail('foobar@gmail.com')`

**Comment by Cyvelnet** [comment]
@fahribaharudin 
i have created a new repo, instead of pushing directly to this repo, due to the repo naming sound misleading and only works for Laravel5 and not above.
you may preview the new repo at

https://github.com/Cyvelnet/laravel-billplz

**Comment by fahribaharudin** [comment]
Alright, cool!
